### ISSUE TITLE
Invalid tileID for flipped objects

### ISSUE THREAD

**Issue by Bioparatus** [fallahn/tmxlite#83] opened 2021-01-30 15:03 UTC
When I parsing an object with the horizontal flip flag set to true I get an invalid tileID (2147484945).
All other (unflipped) IDs are correct and turning off this flag fixes the issue, giving me a valid ID.

Note:
I am not super familiar with your code and how the IDs are calculated, so this might be an issue with Tiled?

**Comment by fallahn** [comment] 2021-01-31 13:34
Thanks for the feedback. I've taken a quick look, and here's what I have so far: flip and rotation flags are, from what I can tell, simply bitmasked onto the UID of the tile. For instance the xml output of Tiled with a single tile placed in a variety of rotations looks like this:

    <tile gid="45"/>
    <tile gid="2684354605"/>
    <tile gid="3221225517"/>

These are the same tile (45) only the second two have flip flags OR'd with the UID - and therefore look something like the incorrect ID you're getting. HOWEVER when I tried the ParseTest project included in the repository the tile IDs are apparently decoded properly - that is they all appear with the ID of 45, with the decoded flip flags on the left. 

![image](https://user-images.githubusercontent.com/5619252/106385197-def1e000-63c6-11eb-85a4-5d3a2e4c82d7.png)

The pertinent code is here if you'd like to test yourself:

https://github.com/fallahn/tmxlite/blob/master/tmxlite/src/TileLayer.cpp#L264

I should add that I didn't write the flag decoding part of the code, it was submitted by a user some time (many years) ago, so until I have time to investigate further I don't know for sure how it works. There could be something else down the line (in tmxlite) which is providing your erronous result. When I have more time I shall investigate further. If you could provide a means of reproducing your problem, such as details of your map file or even a minimal map file which exhibits the error, that would also be a great help, thanks!

**Comment by fallahn** [comment] 2021-02-05 10:25
My apologies, I misread 'Object' as being 'Tile'. Object flags were indeed not being parsed, but it's fixed now!

**Closed** 2021-02-05 10:24 UTC
